### ISSUE TITLE
Tests seem to fail in Exercism whilst passing locally

### ISSUE THREAD

**Issue by aage** [exercism/fsharp#1074]
Concerns the `Diamond` exercise. Could you have a look?

This is the error:
> An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break...

This is my code:
```fsharp
module Diamond

open System

let private fmt width data =
    // function to create whitespace
    let whitespace len = String(' ', len)
    // a string representation of the letter
    let letter = snd data |> sprintf "%c"
    // place space in between if necessary
    let str =
        letter + (fst data |> whitespace) + letter
        |> fun line -> line.Replace(letter + letter, letter)  
    // padding is width minus used space
    let pad = (width - (String.length str)) / 2 |> whitespace
    pad + str + pad

let make letter =
    // the amount of spaces between letters (0, 1, 3, 5...)
    let spaces = 0 :: [ 1 .. 2 .. 49 ]
    // combine letters with amount of space based on index
    let data =
        [ 'A' .. letter ]
        |> List.mapi
            (fun idx letter ->
                let num = spaces[idx]
                (num, letter))
        |> List.rev
    // form the top, middle (single line) and bottom of the diamond
    let top = List.tail data |> List.rev
    let middle = [ List.head data ]
    let bottom = List.tail data
    // partially apply the total width (based on widest line)
    let fmt =
        data |> List.maxBy fst |> fst |> (+) 2 |> fmt
    // concatenate the data after formatting it with padding
    top @ middle  @ bottom
    |> List.map fmt
    |> String.concat "\n"

```

**Comment by ErikSchierboom** [comment]
It seems to be a bug with the test runner:

```fsharp
Unhandled exception. System.ArgumentException: The index was outside the range of elements in the list. (Parameter 'n')
   at Microsoft.FSharp.Collections.PrivateListHelpers.nth[a](FSharpList`1 l, Int32 n) in D:\a\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3697
   at Microsoft.FSharp.Collections.FSharpList`1.get_Item(Int32 index) in D:\a\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3747
   at Exercism.TestRunner.FSharp.Testing.TestResults.visitor@118.VisitSynMemberDefn(SynMemberDefn memberDefn) in /app/Testing.fs:line 156
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 244
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 74
   at Exercism.TestRunner.FSharp.Visitor.SyntaxVisitor.VisitSynTypeDefnRepr(SynTypeDefnRepr stdr) in /app/Visitor.fs:line 683
   at Exercism.TestRunner.FSharp.Visitor.SyntaxVisitor.VisitSynTypeDefn(SynTypeDefn td) in /app/Visitor.fs:line 403
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 244
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 74
   at Exercism.TestRunner.FSharp.Visitor.SyntaxVisitor.VisitSynModuleDecl(SynModuleDecl synMod) in /app/Visitor.fs:line 59
   at Exercism.TestRunner.FSharp.Testing.TestResults.visitor@118.VisitSynModuleDecl(SynModuleDecl moduleDecl) in /app/Testing.fs:line 139
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 237
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 247
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 74
   at Exercism.TestRunner.FSharp.Visitor.SyntaxVisitor.VisitSynModuleOrNamespace(SynModuleOrNamespace modOrNs) in /app/Visitor.fs:line 30
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 244
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 74
   at Exercism.TestRunner.FSharp.Visitor.SyntaxVisitor.VisitInput(ParsedInput input) in /app/Visitor.fs:line 11
   at Exercism.TestRunner.FSharp.Testing.TestResults.findTestMethodBinding(ParsedInput originalTestTree, XmlUnitTestResult xmlUnitTestResult) in /app/Testing.fs:line 162
   at Exercism.TestRunner.FSharp.Testing.TestResults.toTestResult(ISourceText originalTestCode, ParsedInput originalTestTree, XmlUnitTestResult xmlUnitTestResult) in /app/Testing.fs:line 191
   at Exercism.TestRunner.FSharp.Testing.TestResults.toTestResults@203-1.Invoke(a xmlUnitTestResult) in /app/Testing.fs:line 203
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 825
   at Microsoft.FSharp.Collections.SeqModule.SortBy@1106.Invoke(Unit unitVar0) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1107
   at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@471.Invoke(Unit unitVar0) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 471
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 825
   at Exercism.TestRunner.FSharp.Testing.TestResults.parse@218.Invoke(XmlUnitTestResult[] xmlUnitTestResults) in /app/Testing.fs:line 218
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option) in D:\a\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 53
   at Exercism.TestRunner.FSharp.Testing.TestResults.parse(ISourceText originalTestCode, ParsedInput originalTestTree, TestRunContext context) in /app/Testing.fs:line 215
   at Exercism.TestRunner.FSharp.Testing.DotnetCli.runTests(ISourceText originalTestCode, ParsedInput originalTestTree, TestRunContext context) in /app/Testing.fs:line 264
   at Exercism.TestRunner.FSharp.Testing.runTests(TestRunContext context) in /app/Testing.fs:line 298
   at Exercism.TestRunner.FSharp.Program.runTestRunner(Options options) in /app/Program.fs:line 43
   at Exercism.TestRunner.FSharp.Program.main(String[] argv) in /app/Program.fs:line 52
Aborted
```

**Comment by ErikSchierboom** [comment]
@aage This should have been fixed by https://github.com/exercism/fsharp-test-runner/pull/101. Could you check?

**Comment by aage** [comment]
Yes! It works now.

Thank you
